-- Generated by scripts/generate-seed.mjs — do not hand-edit, regenerate instead.
-- Run once per fresh database: wrangler d1 execute <DB_NAME> --remote --file=db/seed.sql

INSERT OR IGNORE INTO admin_config (id, password_hash, updated_at) VALUES (1, '$2b$10$bo82Wm0Zetqqb72b4npZLuSLWJ.jli9x2o0Zgq5MMR5dsNW8eJrjK', 1785059111511);

INSERT OR IGNORE INTO schemes (id, name, description, channel, start_date, end_date, status, version, is_active, created_at, updated_at) VALUES (
  'scheme-july-2026', 'July 2026', 'Official July 2026 Incentives Scheme',
  'MR Channel', '2026-07-01', '2026-07-31', 'Active', '1.0', 1, 1785059111511, 1785059111511
);

INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A07-4-128', 'A07', 'Galaxy A07 5G 4GB/128GB', 'Smartphone', 'A', NULL, 0, '10k-15k', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A07-6-128', 'A07', 'Galaxy A07 5G 6GB/128GB', 'Smartphone', 'A', NULL, 0, '10k-15k', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A17-6-128', 'A17', 'Galaxy A17 5G 6GB/128GB', 'Smartphone', 'A', NULL, 0, '20k-30k', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A17-8-128', 'A17', 'Galaxy A17 5G 8GB/128GB', 'Smartphone', 'A', NULL, 0, '20k-30k', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A17-8-256', 'A17', 'Galaxy A17 5G 8GB/256GB', 'Smartphone', 'A', NULL, 0, '20k-30k', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'F17-6-128', 'F17', 'Galaxy F17 5G 6GB/128GB', 'Smartphone', 'F', NULL, 0, '10k-15k', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'F17-8-128', 'F17', 'Galaxy F17 5G 8GB/128GB', 'Smartphone', 'F', NULL, 0, '15k-20k', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A27-8-128', 'A27', 'Galaxy A27 5G 8GB/128GB', 'Smartphone', 'A', NULL, 0, '30k-40k', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A27-8-256', 'A27', 'Galaxy A27 5G 8GB/256GB', 'Smartphone', 'A', NULL, 0, '30k-40k', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A37-8-128', 'A37', 'Galaxy A37 5G 8GB/128GB', 'Smartphone', 'A', NULL, 0, '40k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A37-8-256', 'A37', 'Galaxy A37 5G 8GB/256GB', 'Smartphone', 'A', NULL, 0, '40k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A37-12-256', 'A37', 'Galaxy A37 5G 12GB/256GB', 'Smartphone', 'A', NULL, 0, '40k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A57-8-128', 'A57', 'Galaxy A57 5G 8GB/128GB', 'Smartphone', 'A', NULL, 0, '40k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A57-8-256', 'A57', 'Galaxy A57 5G 8GB/256GB', 'Smartphone', 'A', NULL, 0, '40k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A57-12-256', 'A57', 'Galaxy A57 5G 12GB/256GB', 'Smartphone', 'A', NULL, 0, '40k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S26-12-256', 'S26', 'Galaxy S26 12GB/256GB', 'Smartphone', 'S', NULL, 1, '70k-100k', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S26-12-512', 'S26', 'Galaxy S26 12GB/512GB', 'Smartphone', 'S', NULL, 1, '100k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S26U-12-256', 'S26 Ultra', 'Galaxy S26 Ultra 12GB/256GB', 'Smartphone', 'S', NULL, 1, '100k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S26U-12-512', 'S26 Ultra', 'Galaxy S26 Ultra 12GB/512GB', 'Smartphone', 'S', NULL, 1, '100k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S26U-16-1TB', 'S26 Ultra', 'Galaxy S26 Ultra 16GB/1TB', 'Smartphone', 'S', NULL, 1, '100k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'ZF7-256', 'Z Fold 7', 'Galaxy Z Fold 7 (256GB)', 'Smartphone', 'Z', NULL, 1, '100k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'ZF7-512', 'Z Fold 7', 'Galaxy Z Fold 7 (512GB)', 'Smartphone', 'Z', NULL, 1, '100k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'ZFl7-256', 'Z Flip 7', 'Galaxy Z Flip 7 (256GB)', 'Smartphone', 'Z', NULL, 1, '100k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'ZFl7-512', 'Z Flip 7', 'Galaxy Z Flip 7 (512GB)', 'Smartphone', 'Z', NULL, 1, '100k+', NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'W8-40', 'Watch 8', 'Watch 8 (40mm)', 'Wearable', NULL, 'Watch', 0, NULL, NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'W8-44', 'Watch 8', 'Watch 8 (44mm)', 'Wearable', NULL, 'Watch', 0, NULL, NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'W8C', 'Watch 8 Classic', 'Watch 8 Classic', 'Wearable', NULL, 'Watch', 0, NULL, NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'W7-40', 'Watch 7', 'Watch 7 (40mm)', 'Wearable', NULL, 'Watch', 0, NULL, NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'W7-44', 'Watch 7', 'Watch 7 (44mm)', 'Wearable', NULL, 'Watch', 0, NULL, NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'W7C', 'Watch 7 Classic', 'Watch 7 Classic', 'Wearable', NULL, 'Watch', 0, NULL, NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'WU', 'Watch Ultra', 'Watch Ultra', 'Wearable', NULL, 'Watch', 0, NULL, NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'B4P', 'Buds 4 Pro', 'Buds 4 Pro', 'Wearable', NULL, 'Buds', 0, NULL, NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'B4', 'Buds 4', 'Buds 4', 'Wearable', NULL, 'Buds', 0, NULL, NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'B3', 'Buds 3', 'Buds 3', 'Wearable', NULL, 'Buds', 0, NULL, NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'B3FE', 'Buds 3 FE', 'Buds 3 FE', 'Wearable', NULL, 'Buds', 0, NULL, NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'Ring', 'Ring', 'Galaxy Ring', 'Wearable', NULL, 'Other', 0, NULL, NULL, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S11U-W', 'S11 Ultra', 'Tab S11 Ultra (WiFi)', 'Tablet', NULL, NULL, 0, NULL, 95000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S11U-5G', 'S11 Ultra', 'Tab S11 Ultra (5G)', 'Tablet', NULL, NULL, 0, NULL, 105000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S11-W', 'S11', 'Tab S11 (WiFi)', 'Tablet', NULL, NULL, 0, NULL, 75000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S11-5G', 'S11', 'Tab S11 (5G)', 'Tablet', NULL, NULL, 0, NULL, 85000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S10P', 'S10 Plus', 'Tab S10 Plus', 'Tablet', NULL, NULL, 0, NULL, 80000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S10FE-W', 'S10 FE', 'Tab S10 FE (WiFi)', 'Tablet', NULL, NULL, 0, NULL, 45000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S10FE-5G', 'S10 FE', 'Tab S10 FE (5G)', 'Tablet', NULL, NULL, 0, NULL, 55000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S10FEP', 'S10 FE+', 'Tab S10 FE+', 'Tablet', NULL, NULL, 0, NULL, 60000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'S10L', 'S10 Lite', 'Tab S10 Lite', 'Tablet', NULL, NULL, 0, NULL, 35000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A11P', 'A11 Plus', 'Tab A11 Plus', 'Tablet', NULL, NULL, 0, NULL, 24000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A11-W', 'A11', 'Tab A11 (WiFi)', 'Tablet', NULL, NULL, 0, NULL, 15000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'A11-5G', 'A11', 'Tab A11 (5G)', 'Tablet', NULL, NULL, 0, NULL, 18000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'GB6P', 'GB6 Pro', 'Galaxy Book6 Pro', 'Notebook', NULL, NULL, 0, NULL, 150000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'GB6U', 'GB6 Ultra', 'Galaxy Book6 Ultra', 'Notebook', NULL, NULL, 0, NULL, 180000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'GB6', 'GB6', 'Galaxy Book6', 'Notebook', NULL, NULL, 0, NULL, 95000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'GB5P', 'GB5 Pro', 'Galaxy Book5 Pro', 'Notebook', NULL, NULL, 0, NULL, 130000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'GB5P360', 'GB5 Pro 360', 'Galaxy Book5 Pro 360', 'Notebook', NULL, NULL, 0, NULL, 140000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'GB5-360', 'GB5 360', 'Galaxy Book5 360', 'Notebook', NULL, NULL, 0, NULL, 110000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'GB5', 'GB5', 'Galaxy Book5', 'Notebook', NULL, NULL, 0, NULL, 85000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'GB4E', 'GB4 Edge', 'Galaxy Book4 Edge', 'Notebook', NULL, NULL, 0, NULL, 75000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'GB4C5', 'GB4 C5', 'Galaxy Book4 C5', 'Notebook', NULL, NULL, 0, NULL, 65000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'GB4C7', 'GB4 C7', 'Galaxy Book4 C7', 'Notebook', NULL, NULL, 0, NULL, 80000, 'Active', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  'GB4-360', 'GB4 360', 'Galaxy Book4 360', 'Notebook', NULL, NULL, 0, NULL, 90000, 'Active', 1785059111511, 1785059111511
);

INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  'rule-dp-slabs-smartphones', 'scheme-july-2026', 'dp_slab_base', 'Smartphone', NULL, NULL, 'Smartphone Base DP Slabs', 'Standard per-unit incentive based on Smartphone DP slabs.', 'Active', '{"slabs":{"10k-15k":{"reward":30,"label":"₹10k–15k"},"15k-20k":{"reward":75,"label":"₹15k–20k"},"20k-30k":{"reward":250,"label":"₹20k–30k"},"30k-40k":{"reward":300,"label":"₹30k–40k"},"40k+":{"reward":400,"label":"₹40k+"},"70k-100k":{"reward":0,"label":"₹70k–100k (Flagship)"},"100k+":{"reward":0,"label":"₹100k+ (Flagship)"}}}', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  'rule-fm-multiplier', 'scheme-july-2026', 'series_multiplier', 'Smartphone', NULL, NULL, 'F & M Series Multiplier Override', 'F & M series models earn a reduced % of the standard DP slab reward.', 'Active', '{"series":["F","M"],"multiplier":0.5,"exceptions":["F17"]}', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  'rule-focus-a57', 'scheme-july-2026', 'focus_model_volume', 'Smartphone', NULL, 'A57', 'A57 Focus Model Volume Slabs', 'Sell higher total volume of A57 to earn higher per-unit rewards.', 'Active', '{"model":"A57","slabs":[{"min":1,"max":2,"reward":550},{"min":3,"max":4,"reward":600},{"min":5,"max":999,"reward":650}]}', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  'rule-focus-a37', 'scheme-july-2026', 'focus_model_volume', 'Smartphone', NULL, 'A37', 'A37 Focus Model Volume Slabs', 'Sell higher total volume of A37 to earn higher per-unit rewards.', 'Active', '{"model":"A37","slabs":[{"min":1,"max":2,"reward":550},{"min":3,"max":4,"reward":600},{"min":5,"max":999,"reward":650}]}', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  'rule-focus-a27', 'scheme-july-2026', 'focus_model_volume', 'Smartphone', NULL, 'A27', 'A27 Focus Model Volume Slabs', 'Sell higher total volume of A27 to earn higher per-unit rewards.', 'Active', '{"model":"A27","slabs":[{"min":1,"max":4,"reward":350},{"min":5,"max":999,"reward":450}]}', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  'rule-a27-kicker', 'scheme-july-2026', 'kicker_bonus', 'Smartphone', NULL, 'A27', 'A27 Volume Kicker Bonus', 'Sell at least 5 A27 units to unlock ₹150 extra per unit on all units.', 'Active', '{"model":"A27","minUnits":5,"rewardPerUnit":150}', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  'rule-flagship-grid', 'scheme-july-2026', 'flagship_achievement_grid', 'Smartphone', NULL, NULL, 'Flagship Achievement Grid', 'Flagship (S & Z series) per-unit earnings based on achievement % band and DP slab.', 'Active', '{"grid":[{"achieveMin":0.8,"achieveMax":0.8999,"dpSlab":"70k-100k","reward":350},{"achieveMin":0.8,"achieveMax":0.8999,"dpSlab":"100k+","reward":400},{"achieveMin":0.9,"achieveMax":0.9999,"dpSlab":"70k-100k","reward":450},{"achieveMin":0.9,"achieveMax":0.9999,"dpSlab":"100k+","reward":500},{"achieveMin":1,"achieveMax":1.1999,"dpSlab":"70k-100k","reward":550},{"achieveMin":1,"achieveMax":1.1999,"dpSlab":"100k+","reward":600},{"achieveMin":1.2,"achieveMax":999,"dpSlab":"70k-100k","reward":650},{"achieveMin":1.2,"achieveMax":999,"dpSlab":"100k+","reward":750}]}', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  'rule-innovative-gate', 'scheme-july-2026', 'target_gate', 'Smartphone', 'Innovative', NULL, 'Innovative Target Gate (80% / 100%)', 'Requires at least 80% achievement on Innovative target to earn payout. Pro-rated between 80% and 100%.', 'Active', '{"segment":"Innovative","minAchievement":0.8,"fullAchievement":1}', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  'rule-flagship-gate', 'scheme-july-2026', 'target_gate', 'Smartphone', 'Flagship', NULL, 'Flagship Target Gate (80%)', 'Requires at least 80% achievement on Flagship target to unlock flagship per-unit earnings.', 'Active', '{"segment":"Flagship","minAchievement":0.8}', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  'rule-wearables-flat', 'scheme-july-2026', 'wearable_flat', 'Wearable', NULL, NULL, 'Wearables Flat Rewards per Model', 'Flat per-unit reward for Watches, Buds, and Rings.', 'Active', '{"flatRewards":{"Watch Ultra":1200,"Watch 8 Classic":1200,"Watch 8":800,"Watch 7 Classic":800,"Watch 7":500,"Other Watches":500,"Buds 4 Pro":800,"Buds 4":600,"Buds 3":400,"Buds 3 FE":200,"Other Buds":200,"Ring":3000}}', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  'rule-wearables-incremental', 'scheme-july-2026', 'volume_incremental', 'Wearable', NULL, NULL, 'Wearables Volume Incremental Bonus', 'Incremental volume bonuses for Watches and Buds when quantity thresholds are crossed.', 'Active', '{"incrementalRewards":{"Watch":[{"min":1,"max":1,"reward":300},{"min":2,"max":999,"reward":500}],"Buds":[{"min":1,"max":1,"reward":100},{"min":2,"max":999,"reward":200}]}}', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  'rule-tablets-scheme', 'scheme-july-2026', 'dp_range_slab', 'Tablet', NULL, NULL, 'Tablet Scheme & DP Slabs', 'Tablet earnings based on DP slabs or focus model rewards. Minimum quantity gate + earning cap apply.', 'Active', '{"minimumGate":2,"maximumEarning":20000,"slabs":[{"dpMin":70000,"dpMax":999999,"reward":800},{"dpMin":40000,"dpMax":69999,"reward":600},{"dpMin":30000,"dpMax":39999,"reward":500},{"dpMin":20000,"dpMax":29999,"reward":300},{"dpMin":15000,"dpMax":19999,"reward":200},{"dpMin":10000,"dpMax":14999,"reward":100}],"focusModels":{"S11 Ultra":1500,"S11":1000,"S10 Plus":1000,"S10 FE":750,"S10 FE+":750,"S10 Lite":500,"A11 Plus":400,"A11":250}}', 1785059111511, 1785059111511
);
INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  'rule-notebooks-scheme', 'scheme-july-2026', 'volume_bonus_gate', 'Notebook', NULL, NULL, 'Notebook Scheme & Volume Bonus', 'Notebook per-model rewards plus extra per unit once the volume gate is met. Earning cap applies.', 'Active', '{"rewards":{"GB6 Pro":3000,"GB6 Ultra":3000,"GB5 Pro":3000,"GB5 Pro 360":3000,"GB6":2000,"GB5 360":2000,"GB5":1500,"GB4 C7":1500,"GB4 Edge":1000,"GB4 C5":1000,"GB4 360":1000,"Other Models":750},"additionalRewardGate":10,"additionalReward":500,"maximumEarning":50000}', 1785059111511, 1785059111511
);
