// Generates db/seed.sql from src/config/schemeJuly2026.json.
// Mirrors the seeding logic that used to live in src/lib/storage.js's
// seedStorage(), so the D1-backed data matches what the app used to
// seed into localStorage on first load.
//
// Run: node scripts/generate-seed.mjs > db/seed.sql
//   (bcryptjs hash for the initial admin password is pre-computed below
//    so this script has no runtime dependency on bcrypt at seed time)

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const seedScheme = JSON.parse(readFileSync(path.join(__dirname, '../src/config/schemeJuly2026.json'), 'utf-8'));

const ADMIN_PASSWORD_BCRYPT_HASH = '$2b$10$bo82Wm0Zetqqb72b4npZLuSLWJ.jli9x2o0Zgq5MMR5dsNW8eJrjK'; // 'admin1234'

function sqlStr(v) {
  if (v === null || v === undefined) return 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
}
function sqlNum(v) {
  if (v === null || v === undefined) return 'NULL';
  return Number(v);
}
function sqlJson(obj) {
  return sqlStr(JSON.stringify(obj ?? {}));
}

const now = Date.now();
const schemeId = 'scheme-july-2026';
const lines = [];

lines.push('-- Generated by scripts/generate-seed.mjs — do not hand-edit, regenerate instead.');
lines.push('-- Run once per fresh database: wrangler d1 execute <DB_NAME> --remote --file=db/seed.sql');
lines.push('');

// Admin config (default password admin1234 — CHANGE THIS after first login)
lines.push(`INSERT OR IGNORE INTO admin_config (id, password_hash, updated_at) VALUES (1, ${sqlStr(ADMIN_PASSWORD_BCRYPT_HASH)}, ${now});`);
lines.push('');

// Scheme
lines.push(`INSERT OR IGNORE INTO schemes (id, name, description, channel, start_date, end_date, status, version, is_active, created_at, updated_at) VALUES (
  ${sqlStr(schemeId)}, ${sqlStr(seedScheme.month || 'July 2026 Scheme')}, ${sqlStr('Official July 2026 Incentives Scheme')},
  ${sqlStr('MR Channel')}, ${sqlStr('2026-07-01')}, ${sqlStr('2026-07-31')}, ${sqlStr('Active')}, ${sqlStr('1.0')}, 1, ${now}, ${now}
);`);
lines.push('');

// Products
(seedScheme.products || []).forEach((p) => {
  lines.push(`INSERT OR IGNORE INTO products (id, base_model, model, category, series, sub_category, flagship, dp_slab, dp, status, created_at, updated_at) VALUES (
  ${sqlStr(p.id)}, ${sqlStr(p.baseModel)}, ${sqlStr(p.model)}, ${sqlStr(p.category)}, ${sqlStr(p.series)}, ${sqlStr(p.subCategory)}, ${p.flagship ? 1 : 0}, ${sqlStr(p.dpSlab)}, ${sqlNum(p.dp)}, ${sqlStr('Active')}, ${now}, ${now}
);`);
});
lines.push('');

function ruleInsert({ id, type, category, segment, model, name, description, data }) {
  return `INSERT OR IGNORE INTO rules (id, scheme_id, type, category, segment, model, name, description, status, data, created_at, updated_at) VALUES (
  ${sqlStr(id)}, ${sqlStr(schemeId)}, ${sqlStr(type)}, ${sqlStr(category)}, ${sqlStr(segment)}, ${sqlStr(model)}, ${sqlStr(name)}, ${sqlStr(description)}, ${sqlStr('Active')}, ${sqlJson(data)}, ${now}, ${now}
);`;
}

// 1. DP Slab Base Rule
lines.push(ruleInsert({
  id: 'rule-dp-slabs-smartphones', type: 'dp_slab_base', category: 'Smartphone',
  name: 'Smartphone Base DP Slabs',
  description: 'Standard per-unit incentive based on Smartphone DP slabs.',
  data: { slabs: seedScheme.dpSlabRewards?.smartphones || {} }
}));

// 2. F & M Series Multiplier
lines.push(ruleInsert({
  id: 'rule-fm-multiplier', type: 'series_multiplier', category: 'Smartphone',
  name: 'F & M Series Multiplier Override',
  description: 'F & M series models earn a reduced % of the standard DP slab reward.',
  data: {
    series: ['F', 'M'],
    multiplier: seedScheme.smartphones?.f_m_series_multiplier || 0.5,
    exceptions: seedScheme.smartphones?.f_m_exceptions || ['F17']
  }
}));

// 3. Focus Models
Object.entries(seedScheme.smartphones?.focusModels || {}).forEach(([model, slabs]) => {
  lines.push(ruleInsert({
    id: `rule-focus-${model.toLowerCase()}`, type: 'focus_model_volume', category: 'Smartphone', model,
    name: `${model} Focus Model Volume Slabs`,
    description: `Sell higher total volume of ${model} to earn higher per-unit rewards.`,
    data: { model, slabs }
  }));
});

// 4. Kicker bonus
if (seedScheme.smartphones?.kicker) {
  const k = seedScheme.smartphones.kicker;
  lines.push(ruleInsert({
    id: 'rule-a27-kicker', type: 'kicker_bonus', category: 'Smartphone', model: k.model,
    name: 'A27 Volume Kicker Bonus',
    description: `Sell at least ${k.minUnits} ${k.model} units to unlock ₹${k.reward} extra per unit on all units.`,
    data: { model: k.model, minUnits: k.minUnits, rewardPerUnit: k.reward }
  }));
}

// 5. Flagship grid
if (seedScheme.smartphones?.flagshipGrid) {
  lines.push(ruleInsert({
    id: 'rule-flagship-grid', type: 'flagship_achievement_grid', category: 'Smartphone',
    name: 'Flagship Achievement Grid',
    description: 'Flagship (S & Z series) per-unit earnings based on achievement % band and DP slab.',
    data: { grid: seedScheme.smartphones.flagshipGrid }
  }));
}

// 6. Target gates
lines.push(ruleInsert({
  id: 'rule-innovative-gate', type: 'target_gate', category: 'Smartphone', segment: 'Innovative',
  name: 'Innovative Target Gate (80% / 100%)',
  description: 'Requires at least 80% achievement on Innovative target to earn payout. Pro-rated between 80% and 100%.',
  data: { segment: 'Innovative', minAchievement: 0.8, fullAchievement: 1.0 }
}));
lines.push(ruleInsert({
  id: 'rule-flagship-gate', type: 'target_gate', category: 'Smartphone', segment: 'Flagship',
  name: 'Flagship Target Gate (80%)',
  description: 'Requires at least 80% achievement on Flagship target to unlock flagship per-unit earnings.',
  data: { segment: 'Flagship', minAchievement: 0.8 }
}));

// 7. Wearable rules
lines.push(ruleInsert({
  id: 'rule-wearables-flat', type: 'wearable_flat', category: 'Wearable',
  name: 'Wearables Flat Rewards per Model',
  description: 'Flat per-unit reward for Watches, Buds, and Rings.',
  data: { flatRewards: seedScheme.wearables?.flatRewards || {} }
}));
lines.push(ruleInsert({
  id: 'rule-wearables-incremental', type: 'volume_incremental', category: 'Wearable',
  name: 'Wearables Volume Incremental Bonus',
  description: 'Incremental volume bonuses for Watches and Buds when quantity thresholds are crossed.',
  data: { incrementalRewards: seedScheme.wearables?.incrementalRewards || {} }
}));

// 8. Tablet rules
lines.push(ruleInsert({
  id: 'rule-tablets-scheme', type: 'dp_range_slab', category: 'Tablet',
  name: 'Tablet Scheme & DP Slabs',
  description: 'Tablet earnings based on DP slabs or focus model rewards. Minimum quantity gate + earning cap apply.',
  data: {
    minimumGate: seedScheme.tablets?.minimumGate || 2,
    maximumEarning: seedScheme.tablets?.maximumEarning || 20000,
    slabs: seedScheme.tablets?.slabs || [],
    focusModels: seedScheme.tablets?.focusModels || {}
  }
}));

// 9. Notebook rules
lines.push(ruleInsert({
  id: 'rule-notebooks-scheme', type: 'volume_bonus_gate', category: 'Notebook',
  name: 'Notebook Scheme & Volume Bonus',
  description: 'Notebook per-model rewards plus extra per unit once the volume gate is met. Earning cap applies.',
  data: {
    rewards: seedScheme.notebooks?.rewards || {},
    additionalRewardGate: seedScheme.notebooks?.additionalRewardGate || 10,
    additionalReward: seedScheme.notebooks?.additionalReward || 500,
    maximumEarning: seedScheme.notebooks?.maximumEarning || 50000
  }
}));

const outPath = path.join(__dirname, '../db/seed.sql');
writeFileSync(outPath, lines.join('\n') + '\n');
console.log(`Wrote ${outPath}`);
